---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

#components:
#  - ../database
#  - ../server
#  - ../watcher

patchesStrategicMerge:
  - |- 
    $patch: delete
    apiVersion: apps/v1
    kind: StatefulSet
    metadata:
      name: database
  - |-
    $patch: delete
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: database