apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../resources/database
  - ../resources/server
  - ../resources/watcher

components:
  - ../components/staging
  - ../components/shared


