apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - service-account.yaml

commonLabels:
  app.kubernetes.io/name: watcher

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: watcher
    literals:
      - api-server=server.tekton-results.svc:50051
      - auth-mode=token
  - name: config-leader-election
    files:
      - _example=leader-election.cfg