---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - allow-argocd-to-manage.yaml
  - https://github.com/redhat-appstudio/infra-deployments/components/o11y/development?ref=main
  - https://github.com/redhat-appstudio/infra-deployments/components/monitoring/prometheus/development?ref=main
