apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - namespace.yaml

namespace: tekton-results

commonLabels:
  app.kubernetes.io/part-of: tekton-results
  app.kubernetes.io/version: 0.4.0
