---
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

resources:
  - argocd-rolebinding.yaml
  - server-route.yaml

configMapGenerator:
  - name: watcher-tls
    options:
      disableNameSuffixHash: true
      annotations:
        service.beta.openshift.io/inject-cabundle: "true"
      labels:
        app.kubernetes.io/name: watcher

patchesStrategicMerge:
  - |-
    $patch: delete
    apiVersion: networking.k8s.io/v1
    kind: Ingress
    metadata:
      name: server
  - |-
    $patch: delete
    apiVersion: cert-manager.io/v1
    kind: Certificate
    metadata:
      name: tekton-results
  - |-
    $patch: delete
    apiVersion: cert-manager.io/v1
    kind: Issuer
    metadata:
      name: tekton-results
  - |-
    $patch: merge
    apiVersion: v1
    kind: Service
    metadata:
      name: server
      annotations:
        service.beta.openshift.io/serving-cert-secret-name: server-tls
  - |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: watcher
    spec:
      template:
        spec:
          volumes:
            - $patch: replace
            - name: tls 
              configMap:
                name: watcher-tls
                items:
                  - key: service-ca.crt
                    path: tls.crt
