apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certificate.yaml
  - clusterrole.yaml
  - clusterrolebinding.yaml
  - deployment.yaml
  - ingress.yaml
  - issuer.yaml
  - service.yaml
  - service-account.yaml

commonLabels:
  app.kubernetes.io/name: server

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: server
    files:
      - config=server.env