---
apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: minio-storage
  namespace: tekton-results
  labels:
    app: minio
  annotations:
    prometheus.io/path: /minio/v2/metrics/cluster
    prometheus.io/port: "9000"
    prometheus.io/scrape: "true"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  image: quay.io/minio/minio:RELEASE.2023-04-20T17-56-55Z
  requestAutoCert: true
  podManagementPolicy: Parallel
  configuration:
    name: minio-configuration
  exposeServices:
    console: true
    minio: true
  features:
    bucketDNS: false
    users:
     - name: minio-user
    buckets:
     - name: "tekton-results"
       region: "not-applicable"
       objectLock: true
  pools:
    - servers: 1
      name: pool-0
      volumesPerServer: 2
      volumeClaimTemplate:
        apiVersion: v1
        kind: persistentvolumeclaims
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
